"""empty message

Revision ID: 21900959b179
Revises: fef82e4e817b
Create Date: 2021-01-23 16:32:14.584010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21900959b179'
down_revision = 'fef82e4e817b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=18), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
