"""add vote model for ORM

Revision ID: 29a798f14dba
Revises: 7be7a6d2b510
Create Date: 2021-02-12 08:45:35.582026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a798f14dba'
down_revision = '7be7a6d2b510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player._id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'vote_id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('wrongGuessVotes')
        batch_op.drop_column('correctGuessVotes')
        batch_op.drop_column('nextVotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nextVotes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('correctGuessVotes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wrongGuessVotes', sa.INTEGER(), nullable=True))

    op.drop_table('votes')
    op.drop_table('vote')
    # ### end Alembic commands ###
