"""empty message

Revision ID: 29f5c1825b17
Revises: 20da94e9d998
Create Date: 2020-12-26 12:13:55.341887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f5c1825b17'
down_revision = '20da94e9d998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_id', table_name='game')
    op.drop_index('ix_player_id', table_name='player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_player_id', 'player', ['id'], unique=False)
    op.create_index('ix_game_id', 'game', ['id'], unique=False)
    # ### end Alembic commands ###
