"""add last_guess to player

Revision ID: 4c1a864f75ab
Revises: 58231f88adba
Create Date: 2021-02-09 16:44:24.944150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1a864f75ab'
down_revision = '58231f88adba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_guess', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('last_guess')

    # ### end Alembic commands ###
