"""empty message

Revision ID: 58231f88adba
Revises: b667eaded914
Create Date: 2021-02-01 11:52:37.185329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58231f88adba'
down_revision = 'b667eaded914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_collections',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_collections')
    # ### end Alembic commands ###
