"""add socket id to player table

Revision ID: 681b17c4039b
Revises: ad6d003a4e13
Create Date: 2021-01-07 18:06:20.966122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681b17c4039b'
down_revision = 'ad6d003a4e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('sid')

    # ### end Alembic commands ###
