"""empty message

Revision ID: 7be7a6d2b510
Revises: 4c1a864f75ab
Create Date: 2021-02-09 16:52:24.529952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be7a6d2b510'
down_revision = '4c1a864f75ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awaitingGuessVote', sa.Boolean(), nullable=True))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('last_guess')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_guess', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('awaitingGuessVote')

    # ### end Alembic commands ###
