"""change gamestate type to enum

Revision ID: 7d9dd7ecb834
Revises: cb9e15ccc067
Create Date: 2021-01-26 14:59:01.456474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9dd7ecb834'
down_revision = 'cb9e15ccc067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
