"""empty message

Revision ID: 9cfaa31e5ae7
Revises: 7d9dd7ecb834
Create Date: 2021-01-26 15:10:10.867947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfaa31e5ae7'
down_revision = '7d9dd7ecb834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('WAITING', 'RUNNING', name='gamestate'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
