"""initial migration

Revision ID: a725247ae9b2
Revises: 
Create Date: 2021-04-08 08:45:24.584283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a725247ae9b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'RUNNING', 'FINISHED', name='gamestate'), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_player_id', sa.String(length=36), nullable=True),
    sa.Column('awaitingGuessVote', sa.Boolean(), nullable=True),
    #sa.ForeignKeyConstraint(['current_player_id'], ['player._id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('player',
    sa.Column('_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('guesses', sa.Integer(), nullable=True),
    sa.Column('guessed', sa.Boolean(), nullable=True),
    #sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    #sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=18), nullable=False),
    sa.Column('password_hash', sa.String(length=94), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.String(length=36), nullable=True),
    #sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    #sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('tag_name', sa.String(length=20), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    #sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ),
    sa.PrimaryKeyConstraint('tag_name', 'collection_id')
    )
    op.create_table('used_collections',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    #sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'collection_id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    #sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    #sa.ForeignKeyConstraint(['player_id'], ['player._id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    #sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'vote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('vote')
    op.drop_table('used_collections')
    op.drop_table('tags')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('player')
    op.drop_table('image')
    op.drop_table('game')
    op.drop_table('collection')
    # ### end Alembic commands ###
