"""add votes to game

Revision ID: b667eaded914
Revises: c0f1702c751d
Create Date: 2021-02-01 07:34:04.767037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b667eaded914'
down_revision = 'c0f1702c751d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correctGuessVotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nextVotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wrongGuessVotes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('wrongGuessVotes')
        batch_op.drop_column('nextVotes')
        batch_op.drop_column('correctGuessVotes')

    # ### end Alembic commands ###
