"""empty message

Revision ID: bd4d8e8fdc70
Revises: fec238b9f4ff
Create Date: 2021-01-26 12:51:57.306700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4d8e8fdc70'
down_revision = 'fec238b9f4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_player_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key("fk_current_player", 'player', ['current_player_id'], ['_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(fk_current_player, type_='foreignkey')
        batch_op.drop_column('current_player_id')

    # ### end Alembic commands ###
