"""add image to character

Revision ID: c0f1702c751d
Revises: 9cfaa31e5ae7
Create Date: 2021-01-27 08:36:30.975800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f1702c751d'
down_revision = '9cfaa31e5ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key("character_image_fk", 'image', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(character_image_fk, type_='foreignkey')
        batch_op.drop_column('image_id')

    op.drop_table('image')
    # ### end Alembic commands ###
