"""add name and password to game

Revision ID: c9d2535522d4
Revises: 29f5c1825b17
Create Date: 2021-01-06 11:56:47.254861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d2535522d4'
down_revision = '29f5c1825b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('game', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'password_hash')
    op.drop_column('game', 'name')
    # ### end Alembic commands ###
