"""empty message

Revision ID: cb9e15ccc067
Revises: bd4d8e8fdc70
Create Date: 2021-01-26 14:41:46.625069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9e15ccc067'
down_revision = 'bd4d8e8fdc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guessed', sa.Boolean(), nullable=True))
        batch_op.drop_column('isOwnTurn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isOwnTurn', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('guessed')

    # ### end Alembic commands ###
