"""empty message

Revision ID: ec17d8d22396
Revises: c9d2535522d4
Create Date: 2021-01-06 11:59:28.395296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec17d8d22396'
down_revision = 'c9d2535522d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('name', sa.String(length=20), nullable=True))
    op.add_column('game', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'password_hash')
    op.drop_column('game', 'name')
    # ### end Alembic commands ###
