"""add foreign key constraints

Revision ID: fc57c4e0512a
Revises: a725247ae9b2
Create Date: 2021-04-08 09:16:57.632837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc57c4e0512a'
down_revision = 'a725247ae9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_foreign_key('collection_id_character', 'collection', ['collection_id'], ['id'])
        batch_op.create_foreign_key('image_id_character', 'image', ['image_id'], ['id'])

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint('game_id', ['id'])
        batch_op.create_foreign_key('current_player_id', 'player', ['current_player_id'], ['_id'])

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_unique_constraint('image_id', ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint('player_id', ['_id'])
        batch_op.create_foreign_key('game_id_player', 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key('character_id_player', 'character', ['character_id'], ['id'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint('tag_id', ['name'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_foreign_key('tag_name_tags', 'tag', ['tag_name'], ['name'])
        batch_op.create_foreign_key('collection_id_tags', 'collection', ['collection_id'], ['id'])

    with op.batch_alter_table('used_collections', schema=None) as batch_op:
        batch_op.create_foreign_key('collection_id_used_collections', 'collection', ['collection_id'], ['id'])
        batch_op.create_foreign_key('game_id_used_collection', 'game', ['game_id'], ['id'])

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_foreign_key('player_id_vote', 'player', ['player_id'], ['_id'])
        batch_op.create_foreign_key('game_id_vote', 'game', ['game_id'], ['id'])

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_foreign_key('vote_id_votes', 'vote', ['vote_id'], ['id'])
        batch_op.create_foreign_key('game_id_votes', 'game', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('game_id_votes', type_='foreignkey')
        batch_op.drop_constraint('vote_id_votes', type_='foreignkey')

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('game_id_vote', type_='foreignkey')
        batch_op.drop_constraint('player_id_vote', type_='foreignkey')

    with op.batch_alter_table('used_collections', schema=None) as batch_op:
        batch_op.drop_constraint('game_id_used_collection', type_='foreignkey')
        batch_op.drop_constraint('collection_id_used_collections', type_='foreignkey')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('collection_id_tags', type_='foreignkey')
        batch_op.drop_constraint('tag_name_tags', type_='foreignkey')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tag_id', type_='unique')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('character_id_player', type_='foreignkey')
        batch_op.drop_constraint('game_id_player', type_='foreignkey')
        batch_op.drop_constraint('player_id', type_='unique')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_id', type_='unique')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('current_player_id', type_='foreignkey')
        batch_op.drop_constraint('game_id', type_='unique')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('image_id_character', type_='foreignkey')
        batch_op.drop_constraint('collection_id_character', type_='foreignkey')

    # ### end Alembic commands ###
