"""empty message

Revision ID: fec238b9f4ff
Revises: 7a4c1e13d884
Create Date: 2021-01-26 11:53:26.861814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec238b9f4ff'
down_revision = '7a4c1e13d884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guesses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('isOwnTurn', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('isOwnTurn')
        batch_op.drop_column('guesses')

    # ### end Alembic commands ###
